### ISSUE TITLE
First click test on nav and context links

### ISSUE THREAD

**Issue by Tosin-Balogun** [nhsuk/nhsuk-service-manual#1048]
# What
We need to create a first click A/B test to get a pulse-check for some of the ideas we have taken forward, like the section label change and the contextual links
# Why
This should give us confidence if our idea(s) is doing what we expect or gives us something to think about in terms of making small tweaks
# Related
#1001 #1000 #1003

**Comment by amyj2110** [comment]
[First click test preview](https://github.com/nhsuk/nhsuk-service-manual/issues/1000#issuecomment-799572673)

**Comment by Tosin-Balogun** [comment]
> [First click test preview](https://github.com/nhsuk/nhsuk-service-manual/issues/1000#issuecomment-799572673)

Looks great @amyj2110. The questions and sequencing flows well 😄 

How do we get this to reach the whole community so many people both within and outside NHSD can participate? @lucyha

**Comment by Tosin-Balogun** [comment]
This is ready to be sent out tomorrow, we plan to use the following channels to reach out community
- NHSUK slack (user research, content, design, delivery, general, front-end, ucdgrads, dsdgrads)
- NHS App slack
- NHS login slack
- Screening slack
- Public slack (general)
- Style council
- Twitter

**Comment by amyj2110** [comment]
### Results links
["Community" VS "Community and contribution"](https://nhsd-confluence.digital.nhs.uk/display/SMDS/Community+VS+Community+and+contribution)
[Share your findings button location](https://nhsd-confluence.digital.nhs.uk/x/NqCzCw)

### Summary
- There was not a massive difference around adding "... and contribution" to the community link. People were able to click the "Community and contribution" link faster than just "Community". 
- More people clicked the top main navigation when the link was "Community and contribution".
- People were more likely to click the "Share your findings" button when it was a part of the main page, rather than as a part of the side navigation.
- In both tests, a high proportion of people were clicking the "get in touch" links. We need to investigate what "get in touch" means to people and how we can distinguish between people contacting us for support and contributions.
