### ISSUE TITLE
Error summary example

### ISSUE THREAD

**Issue by chrimesdev** [nhsuk/nhsuk-service-manual#1156]
## Description

The Error summary example does not follow the 1 thing per page principal by showing errors for 2 unrelated questions "Date of birth must be in the past" and "Enter a postcode, like AA1 1AA". We wouldn't recommend asking these 2 questions on a single question page in a real service, so the example error summary should only relate to a single "thing".

https://service-manual.nhs.uk/design-system/components/error-summary

**Comment by cjforms** [comment]
I know about the history of this because I was there when the original error summary box was designed. This was around end of March/early April 2015. I think I remember the dates relatively clearly, because it was all just before the big fire in Holborn that meant we were all sent home from GDS at zero notice and not allowed back into the office for several days. Very unusual then. https://www.bbc.co.uk/news/uk-england-london-32231725

It was a collaboration between Leonie Watson, expert in accessible markup and herself a screen-reader user, and Gemma Leigh, at that time the front-end dev working on GOV.UK 'elements' which was the precursor to the design system. I was sort of being the content designer. 

Leonie, myself and Gemma were working to resolve a previous inaccessible error thing and this component and advice was created in quite a hurry. I was trying to come up with the content design for a version that would work with a page that only had one thing on it, and for a version that would work with a page with many things on it. But, that content wasn't testing well and there was a risk that if we went for something that dealt with both sorts of page, we might delay releasing the urgent thing which was to have something that was accessible *at all*. So as a team, we decided that we would opt for just the advice that worked for a page that had several things on it, because that version sort of worked for the only-one-thing page too. 

The advice that we now know as 'begin prototyping with one thing per page' actually started to be published in July 2015, when Tim Paul published his blog post: https://designnotes.blog.gov.uk/2015/07/03/one-thing-per-page/ 
I wrote my blog post https://www.effortmark.co.uk/no-accordions-choose-form-structure/
and we wrote and published the first version of the 'Form Structure' page for the Service Manual that asked designers to start with one thing per page.

At that time, we had other priorities and we did not go back to change the error summary guidance. 

So ... that explains why the error summary guidance was a bit inconsistent with "one thing per page" originally. 

As you can see, it's definitely been a while and I'm sure there have been a few iterations of the guidance since then, but I can't tell you what they might be because I haven't been involved. The one thing I'm relatively certain about is that people who have worked on it more recently wouldn't be aware of the compromise we made originally or why.

**Comment by chrimesdev** [comment]
this is done, I will transfer @cjforms comment to the error summary issue as its quite useful to know for future.
