### ISSUE TITLE
EPIC: WCAG 2.2 accessibility audit/review and update of design system

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#1832]
### What
- Talk with GOV.UK about their plans to update the GOV design system
- Audit and review the NHS design system against WCAG 2.2 
- Recommend changes to design system to bring it into line with WCAG 2.2
- Update components and patterns, test and publish

The NHSD Central UCD team is working on an accessibility strategy that will cover this. Even if the review and audit is carried out by another team (e.g. an accessibility lead), the service manual team will need to develop and update components and patterns, probably involving:
- design
- dev
- content design
- user research

### Why
- WCAG 2.2 is expected to be published early 2023. NHS services will probably have 6 to 12 months to comply. NHS services will need up to date, compliant styles, components and patterns. 

### Related issues
- EPIC: Accessibility guidance (update + assess existing guidance against WCAG 2.2) #669

### Should

**Comment by Moll-Lee** [comment]
With WCAG2.2 guidelines due to be published imminently, the NHS Service manual team want to work with accessibility leads across NHS England to ensure our content meets the new standards. An approach to this could be completing a full audit of the NHS front end and design system and publishing a report to our users with upgrades so that we can bring as many of our users up to 2.2 guidelines as efficiently as possible. We will also need to update our content to reflect any changes or additions brought in as part of 2.2 guidelines. This work will be a two pronged approach to ensure NHS branded services are compliant at the earliest opportunity. We are currently discussing resource options and approaches to this and this ticket will be updated as soon as that information is firmed up.

**Comment by anandamaryon1** [comment]
New guidance published: 17 April 2024
