### ISSUE TITLE
Draft `nhsuk-link--no-visited-state` modifier guidance

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#665]
## What

Add guidance for the `nhsuk-link--no-visited-state` modifier in the link styles.

## Why

The `nhsuk-link--no-visited-state` modifier is included in the Frontend v4.0.0 release.

## Related issues

[Frontend issue 643](https://github.com/nhsuk/nhsuk-frontend/issues/643)

## Done when

- [x] add code example
- [x] draft guidance
- [x] content review - @sarawilcox

**Comment by davidhunter08** [comment]
Hi @sarawilcox - this is ready for a content review on [PR 730](https://github.com/nhsuk/nhsuk-service-manual/pull/730).

<img width="882" alt="Screenshot 2020-10-15 at 14 44 31" src="https://user-images.githubusercontent.com/14331000/96137845-0c3c8000-0ef5-11eb-8b93-0211c2baa6c9.png">

**Comment by sarawilcox** [comment]
This text is quite technical. I understand the aim and the scenario but don't understand the bit about "modifier classes". I would struggle to express it another way and, even if I could, would probably risk muddying the waters for knowledgeable users. Given that the GDS system has been using this wording, I’m comfortable leaving it as it is so long as new designers understand it. What do @Tosin-Balogun and @henocookie make of this paragraph? Do you know what a "modifier class" is, and does it matter?

**Comment by AdamChrimes** [comment]
@sarawilcox if we change it from "modifier class", I think we risk it making less sense to people who are more likely need to use it.

**Comment by sarawilcox** [comment]
@davidhunter08 I forgot to mention. We'll need to update the Date updated to October 2020.

**Comment by sarawilcox** [comment]
Yes, @AdamChrimes, that's what I was afraid of. So long as the core audience understands it, I'm OK with this.

**Comment by henocookie** [comment]
I'd understand "modifier class". I'd possibly argue using just "class" would be understandable, but I imagine "modifier class" is the technically correct term.

**Comment by cjforms** [comment]
I'm less bothered by the 'modifier class', which less important than the name of the thing that you are describing, than by the 'when ' that's part-way down the sentence.

How about turning it around so that it says:
If you have links where distinguishing between visited and unvisited is unhelpful, for example <insert example as above> then use the "nhsuk-link--no-visited-state" modifier class to turn off the "visited" state. 

(In fact, the term 'modifier class' is redundant for me, as I think that you could write 'use "nhsuk-link--no-visited-state" to turn off..." and it would still be clear what you mean. But as @henocookie pointed out that 'modifier class' is OK and as I'm not the heartland of your users, I'd keep the term in the text).

**Comment by sarawilcox** [comment]
Thanks @cjforms. Yes, good spot. I've brought the "if" to the start of the sentence.

**Comment by sarawilcox** [comment]
Content reviewed.
