### ISSUE TITLE
Audit missing components from the service manual (that are in the frontend)

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#711]
## What

Audit missing components from the service manual that are in the frontend.

## Why

We need to know the full list of components and understand how they are being used by other teams/services.

## Done when

- [x] create a list of all the components

**Comment by cjforms** [comment]
Suggestion to add to this list:
- if a component is being used that is not in the service manual, think about whether there's a way to change the thing so that it only uses components in the service manual

Rationale: sometimes people make a new component because it seemed easier and quicker at the time than working out how to make the system with the more restricted selection in the service manual, and in the short term this can be true. But in the longer term, every extra component you add to the manual creates a continuing maintenance load (internal cost) and every extra different component that a user may encounter creates extra cognitive effort (external cost)
