### ISSUE TITLE
Write up community contribution usability testing

### ISSUE THREAD

**Issue by henocookie** [nhsuk/nhsuk-service-manual#825]
## What
Write up a summary of the findings and recommendation following the community contribution usability tests.

## Why
So the team can refer back to the research when planning and designing ways to address user needs.

## Relates to
EPIC: Community contribution #685

## Depends on
#822 

## Who needs to know about this
@amyj2110 and @henocookie, user researchers

## Done when
Tasks we need to do:
- [x] Document findings in a presentable format
- [x] Share a link to the findings with the service manual team and community
- [x] Write a summary in GitHub ticket

**Comment by amyj2110** [comment]
# Usability testing findings summary

## Thoughts on the service manual in general
- People find the service manual useful in their day-to-day job. People mention things like time-saving, and having everything in one place as useful features. They also like that the service manual gives them a place to find and use things that have already been tested and approved.
- The service manual is used for people to check what they're doing is "right". People see it as a place to refer others to, and can be "the final word" when discussing or debating certain thing.

## People are likely to contact the service manual team before starting a contribution​
- Most people will either contact the person they know best in the service manual team or the person they think is most "relevant"​. For example, if they know David Hunter is the designer on the service manual, they will be most likely to go to him for a design query. Alternately, if they personally know Sara Wilcox, who is also working on the service manual, they will also be more likely to speak to her first.
- People were also open to reaching out to anyone they saw on the GitHub repo, especially people who had already commented on an issue they were interested in,.
- People wanted to speak to someone familiar or who knew what was going on​.
- It was also seen to be "polite" to contact someone if you were going to work on or edit "their" thing. This was especially true of content designers and when asking about small changes.​
- Some people also talked about wanting to share a contribution draft in another programme or website. One person had used Microsoft Word, and another used Confluence to write up their contribution before putting it into GitHub. People wanted to do this so they could share and check with their team and members of the service manual team.
- Some people mentioned that they would like to be shown how to contribute. They talked about wanting to have a service manual team member talk them through everything, and show them where to go and what to do.

## People identified "low level" ways that they thought they had contributed
- Many mentioned feeling like they had contributed through attending design meet-ups and content style council sessions.
- Others talked about interacting with a small number of GitHub issues or just "joining in with the conversation".

## People seem to have their own different ways to find and access the service manual
- People split between searching for the "NHS service manual" in a search engine, selecting it from their recently or most visited websites, or from a saved bookmark on their web browser.
- Those who had it bookmarked tended to have a specific section of the service manual bookmarked. This tended to be either the design system, the content style guide or the front end library, and was usually linked to their job role. For example, designers were more likely to have the design system bookmarked.
- Most had GitHub log in information saved on their browser, or written down somewhere. Those who did not have easy access to their log in information tended to be stuck when their usual passwords did not work. 
- Designers, content designers and researchers mentioned that they tend not to access GitHub on a daily basis, and therefore struggled to remember their log in information if it wasn't saved in their browser.

## Most people didn't know how to start a contribution
- When asked to start a brand new contribution, most people didn't know where to go to start this.​
- People attempted to go into the "Get in touch" link at the bottom of service manual pages, or expected to see a direct link to contribute in the relevant area, design system or content style guide.
- People seemed to know that GitHub was involved at some point, but couldn't find the direct link to GitHub that they were looking for.

## Most people didn't click "Community" without being prompted
- When asked to find the place to make a contribution, most people did not instinctively click into the "Community" section of the service manual website. 
- People were also unsure of what would be in the "Community" section.

## Most people would be willing to identify and share errors, but would not expect to fix errors themselves
This finding relates most to Scenario 2:
> You have noticed a mistake in the service manual. Show me how you would go about rectifying this yourself.​
- Some people didn't feel comfortable making a change like this​ in the service manual. This just wasn't the kind of contribution people were interested in making.
- Most people wanted to share the error and let the service manual team fix it themselves​.

## Most people didn't recognise the process and didn't know if they could change the code 
This finding relates most to Scenario 2:
> You have noticed a mistake in the service manual. Show me how you would go about rectifying this yourself.​
- People were uncertain whether they were allowed to make changes to the service manual code​.
- They were also unsure of the actual process to change the code and whether that related to "fixing an error"​. This included being unsure about the code they saw on the page; people were very uncertain that it was the same code for the page they had just been looking at, resulting in a lot of to-ing and fro-ing between the pages to check.

## Most people were aware that they could find something at the bottom of the page to flag errors or change something about a page
This finding relates most to Scenario 2:
> You have noticed a mistake in the service manual. Show me how you would go about rectifying this yourself.
- People instinctively scrolled to the bottom of the page, most stating that it was a "standard" to find some sort of "contact us" or "get in touch" option at the bottom of the page.
- People noticed and would use the "get in touch" link to propose changes or add research, rather than using the links under "Help improve this page" to propose a change.

## Most people would look at what others share to get an idea of what they would share​
This finding relates most to Scenario 3:
> Some user research you were part of recently showed that an experimental component wasn't really fit for use. Show me how you would go about sharing your evidence on the service manual.​
- People were intrigued to read what other people had written​.
- This was often to help them figure out whether they should post, or how they might be able to contribute to the conversation​. They also wanted to check to make sure no one else had already made the point they wanted to make. 
- Some people would also browse for similar looking issues in the backlog, to check if their contribution had already been mentioned.
- When checking the backlog in GitHub, most people quickly scrolled down the most recent issues and seemed to skim and scan the contents.

## Most people wouldn't know exactly what to share, but were happy to share something
- When starting a brand new contribution, people weren't necessarily sure which parts of their work they should share. Most mentioned screenshots or links to a prototype, and a link to the code or repository they had been working on. Although some people were unsure about sharing password protected URLs.
- Despite being unsure, people were still very keen to share something, showing that there is some enthusiasm for making a contribution.
- People mainly felt confident about sharing their work. Although some seemed to put the service manual on a pedestal and feel like they were "unworthy" to comment on it or contribute to it.

## People were unaware of labels on GitHub and what their purpose was
- Most people did not add labels because they weren't aware of them or their purpose on GitHub. 
- People assumed that labels might be added automatically or by the service manual team, after something had been submitted.

## Most people were unaware of tags on GitHub and would be unlikely to use them
- Most people seemed unaware that they could tag someone in a brand new contribution. When asked, they were unsure who they would tag.
- People would only tag someone if they were related or relevant to the discussion, like someone who had previously commented. Some would not tag anyone in a comment.
- People did not really mention that they would tag other members of their team. This could be because they will be checking everything with their team before they contribute, so might not feel that the other members of their team have anything further to add.

## Most people don't understand the terminology and interface on GitHub and were reluctant to use it
- There was a general lack of understanding about how GitHub worked and how to use it, with some people mentioning feelings of fear and uncertainty when using it. Words like "terrifying" and "daunting" were used.
- GitHub was seen as somewhere specifically for "techies" or developers, and people felt disadvantaged if they weren't in one of these groups.

## People would be more likely to discuss topics on Slack, but wouldn't share these discussions without being asked
- A lot of people mentioned using Slack for discussions around content and design topics. However, they would be unlikely to then share those conversations in GitHub, unless they were asked to by a service manual team member.

## People were unsure what would happen once they had submitted a brand new contribution
- The process for "what happens next" was unclear to people. They were unsure how involved they would then have to be, and who would be taking it forward.

## People did not really have any expectations after they made a comment
- People assumed they would make a comment on an issue and that would be it. Some thought the service manual team might get in touch, but there wouldn't be anything to do with it afterwards.
- Most thought that the other people in the discussion might receive a notification when they left their comment, and this might prompt other replies. However, people said that they probably wouldn't be religiously checking back to the page, unless they had left a question that needed an answer.

**Comment by davidhunter08** [comment]
> People attempted to go into the "Get in touch" link at the bottom of service manual pages, or expected to see a direct link to contribute in the relevant area, design system or content style guide.

The tree test supports this finding.

![tree-test-contribution](https://user-images.githubusercontent.com/14331000/100650500-edc30480-333b-11eb-9804-0635d40e4f2d.png)

**Comment by davidhunter08** [comment]
<img width="1076" alt="Screenshot 2020-11-30 at 18 47 22" src="https://user-images.githubusercontent.com/14331000/100650940-9ffacc00-333c-11eb-96d4-d7d6bc72ecda.png">

**Comment by henocookie** [comment]
In addition to @amyj2110's excellent findings summary, we also created a presentation to show high-level findings and recommendations with the team. You can find the presentation here: https://hscic365.sharepoint.com/:p:/s/servicemanual/EUcth2y0pmxEvhh8zo1WxAQBe3wq9SG2TfD8bS4o2ZMJcw?e=KyCtl9

If you're outside of NHS Digital and can't access this presentation, please reply or message me and I'll get you access!
