### ISSUE TITLE
Upgrading nhs.uk services to use the latest version of the frontend library

### ISSUE THREAD

**Issue by lucyha** [nhsuk/nhsuk-service-manual#850]
## What

We need to make sure that all of our services are using the latest version of the NHS.UK frontend library. We also need to look at a better way of teams managing these version updates

- [x] Audit our services to find out what versions of the frontend library they are using and how
- [x] Update our services to use the latest NHS.UK frontend (mainly Wagtail)
- [ ] Investigate a better way of maintaining NHS.UK frontend library versions

Auditing has begun here: https://confluence.service.nhs.uk/display/SMDS/NHS+website+%28NHS.UK%29+services+using+NHS.UK+frontend

**Comment by sarawilcox** [comment]
@AdamChrimes @davidhunter08 Hi, I met with Paul and Mark. Paul's going to crack on with the work and then report back to us plus Bal next week.

I took away 3 things for us to look at in our team:
- the feature card - which will appear in Wagtail and is in the frontend but not yet in the card component in the service manual. What were we going to do about this, @davidhunter08?
- @AdamChrimes, would you be able to remove the full stops in cards in the frontend so that they match the examples in the service manual, please?
- Also, after recent conversations with Michael C, I think we need a colon after the word Important in span so that screen readers pause before announcing a custom heading. If it just runs on without a pause, there is potential to confuse. Can we do that in the examples in the front end and the service manual, please?

**Comment by davidhunter08** [comment]
Thanks @sarawilcox.

The feature card is a tricky one. The plan is to use a feature card for the 'Do and don't list' pattern - see https://github.com/nhsuk/nhsuk-service-manual/issues/695. So until we do that piece of work, I am not sure what guidance we could add to the service manual for a feature card? Happy to discuss it further.

I can look at the other 2 items, removing the full stops and adding a colon.

**Comment by sarawilcox** [comment]
@AdamChrimes, do you know if the warning callout has already been updated in Wagtail, please? Or is it part of the work that's going on at the moment? (@mcheung-nhs was asking.)

Also, you know that we updated the frontend with a colon after the word "important" in the warning callout? Is that on the list of things to do in Wagtail too?

@lucyha, is there a way to have sight of changes we're making across:
- frontend
- service manual
- Wagtail
@AdamChrimes @davidhunter08, please say if you have thoughts about this.

**Comment by chrimesdev** [comment]
This was done, its now an going process everytime a version of the FE library is released. Hopefully handled by teams on NHS.UK
