### ISSUE TITLE
Hypothesis: Create new issue templates by contribution type

### ISSUE THREAD

**Issue by Tosin-Balogun** [nhsuk/nhsuk-service-manual#996]
# What
If we create GitHub issue templates specific for the different types of contribution

Then that'll make it easier for people to contribute

# We know this works;
- If users tell us they find it useful compared to our old one. 
- We can check this in usability to see how it performs
- We can monitor the number of users contributing using new templates

# Task list
- [x] Baseline the as-is situation
- [x] Create templates
- [x] Content review

# Related
EPIC: Help users understand how to use GitHub for contributing #991

**Comment by davidhunter08** [comment]
[Issue template thinking on Mural](https://app.mural.co/invitation/mural/nhsdigital8118/1619432558590?sender=u8135d283f508b4b1f9109566&key=aced0913-1c37-4591-a031-d43a9548d3c4)

**Comment by davidhunter08** [comment]
@sarawilcox These templates are ready for a content review.

**Comment by sarawilcox** [comment]
Hi @davidhunter08, I'm having an initial look at this issue. I wanted to check in with you about what to call them before making any changes. In fact, I'm wondering if you would mind making some naming changes to make things more consistent and then I'll go through it in more detail? (Just because I'm short of time.)

My first thought is just to have one naming system for the 3 different kinds of issue. How about?
1 Report a problem - and then in the template give some examples: like a bug, broken link or typo
2 Ask a question 
3 Propose a new feature or improvement

Would that work? Using that same wording across the templates and prototype? 

Rather than having the word "Issue" in the heading, would it be better to say "Template for reporting a problem" for example? (Not sure.)

**Comment by davidhunter08** [comment]
Thanks @sarawilcox - the one naming system is a lot better. I've updated them on GitHub, I just now need to update the prototype.

<img width="1274" alt="Screenshot 2021-06-03 at 09 44 13" src="https://user-images.githubusercontent.com/14331000/120615739-8011a580-c450-11eb-8deb-367451341c19.png">

https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/new/choose

I need to look into where the heading prefix of "Issue" comes from and check if it is something we can change.

**Comment by sarawilcox** [comment]
Hi @davidhunter08, for when you get back from leave:
- would you mind changing the label "enhancement" to "new feature" please? and the "bug" one to "problem"?  
I've been through the templates now. What do you think?

**Comment by davidhunter08** [comment]
Thanks @sarawilcox  - I'll take a look when I get back.

The latest version of the contribution guidance prototype is on https://github.com/nhsuk/nhsuk-service-manual/issues/1222.

**Comment by davidhunter08** [comment]
Looks good @sarawilcox.

So far so good, as people have already started using the templates. 

We will usability test them along with the new (in prototype) contribution guidance. I'll make a note of that on another issue.
